// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/badword.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BadwordService_SayBadword_FullMethodName = "/badword.BadwordService/SayBadword"
)

// BadwordServiceClient is the client API for BadwordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BadwordServiceClient interface {
	SayBadword(ctx context.Context, in *BadwordReq, opts ...grpc.CallOption) (*BadwordRes, error)
}

type badwordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadwordServiceClient(cc grpc.ClientConnInterface) BadwordServiceClient {
	return &badwordServiceClient{cc}
}

func (c *badwordServiceClient) SayBadword(ctx context.Context, in *BadwordReq, opts ...grpc.CallOption) (*BadwordRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BadwordRes)
	err := c.cc.Invoke(ctx, BadwordService_SayBadword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadwordServiceServer is the server API for BadwordService service.
// All implementations must embed UnimplementedBadwordServiceServer
// for forward compatibility.
type BadwordServiceServer interface {
	SayBadword(context.Context, *BadwordReq) (*BadwordRes, error)
	mustEmbedUnimplementedBadwordServiceServer()
}

// UnimplementedBadwordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadwordServiceServer struct{}

func (UnimplementedBadwordServiceServer) SayBadword(context.Context, *BadwordReq) (*BadwordRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayBadword not implemented")
}
func (UnimplementedBadwordServiceServer) mustEmbedUnimplementedBadwordServiceServer() {}
func (UnimplementedBadwordServiceServer) testEmbeddedByValue()                        {}

// UnsafeBadwordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadwordServiceServer will
// result in compilation errors.
type UnsafeBadwordServiceServer interface {
	mustEmbedUnimplementedBadwordServiceServer()
}

func RegisterBadwordServiceServer(s grpc.ServiceRegistrar, srv BadwordServiceServer) {
	// If the following call pancis, it indicates UnimplementedBadwordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadwordService_ServiceDesc, srv)
}

func _BadwordService_SayBadword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BadwordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadwordServiceServer).SayBadword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadwordService_SayBadword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadwordServiceServer).SayBadword(ctx, req.(*BadwordReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BadwordService_ServiceDesc is the grpc.ServiceDesc for BadwordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadwordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "badword.BadwordService",
	HandlerType: (*BadwordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayBadword",
			Handler:    _BadwordService_SayBadword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/badword.proto",
}
